import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type SupportedLanguage = 'mr' | 'hi' | 'en' | 'gu' | 'ta' | 'bn' | 'or' | 'ml' | 'te' | 'kn';

export interface LanguageOption {
  code: SupportedLanguage;
  label: string;
  nativeLabel: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी' },
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
  { code: 'or', label: 'Odia', nativeLabel: 'ଓଡ଼ିଆ' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
];

const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  mr: {
    knots: 'नॉट्स',
    meters: 'मीटर',
    mps: 'मी/से',
    high_tide: 'भरती',
    nw: 'वायव्य',
    high_probability_pfz: 'उच्च संभाव्यता मासेमारी क्षेत्र',
    pfz_type: 'संभाव्य मासेमारी क्षेत्र',
    cyclone_warning: 'चक्रीवादळ इशारा',
    hazard: 'धोका',
    coast_guard_station: 'तटरक्षक दल स्टेशन',
    rescue_type: 'बचाव',
    safe_navigation_route: 'सुरक्षित नेव्हिगेशन मार्ग',
    route_type: 'मार्ग',
    imbl_buffer: 'आंतरराष्ट्रीय सागरी सीमा रेषा बफर',
    boundary_warning: 'सीमा इशारा',
    approaching_imbl: 'आंतरराष्ट्रीय पाण्याजवळ',
    computed_route: 'उंच लाटा टाळणारा मार्ग',
    type_query: 'तुमचा प्रश्न येथे टाइप करा...',
    stop: 'थांबा',
    mic: 'माईक',
    send: 'पाठवा',
    current_sea_state: 'सध्याची समुद्राची स्थिती',
    wind_speed: 'वाऱ्याचा वेग:',
    wind_dir: 'वाऱ्याची दिशा:',
    wave_length: 'लाटेची लांबी:',
    wave_speed: 'लाटेचा वेग:',
    temperature: 'तापमान:',
    tide: 'भरती-ओहोटी:',
    pfz: 'संभाव्य मासेमारी क्षेत्र',
    alerts: 'सूचना',
    imbl: 'आंतरराष्ट्रीय सागरी सीमा रेषा',
    rescue: 'बचाव',
    safe_route: 'सुरक्षित मार्ग',
    zone_details: 'क्षेत्र तपशील',
    confidence: 'आत्मविश्वास:',
    severity: 'तीव्रता:',
    contact: 'संपर्क:',
    close: 'बंद करा',
    permission_denied: 'परवानगी नाकारली',
    mic_access_required: 'व्हॉइस AI वापरण्यासाठी मायक्रोफोन ऍक्सेस आवश्यक आहे.',
    ai_error_fallback: 'AI सेवेशी कनेक्ट करण्यात अयशस्वी. ऑफलाइन कॅशेवर परत येत आहे...',
    app_title: 'ओर्का',
    nav_home: 'मुख्य',
    nav_map: 'नकाशा',
    nav_ai: 'ओर्का एआय',
    nav_alerts: 'सूचना',
    nav_profile: 'प्रोफाइल',
    risk_low: 'कमी धोका',
    risk_moderate: 'मध्यम धोका',
    risk_high: 'जास्त धोका',
    ask_orca: 'ओर्काला विचारा',
    emergency_sos: 'आणीबाणी (SOS)',
    ocean_conditions: 'समुद्राची स्थिती',
    fishing_intelligence: 'मासेमारी माहिती',
    cached_banner: 'कॅश केलेला डेटा — जुनी माहिती',
    offline_mode: 'ऑफलाइन मोड',
    confirm: 'नक्की करा',
    cancel: 'रद्द करा',
    retry: 'पुन्हा प्रयत्न करा',
    wet_hand_mode: 'ओले हात आणि सूर्यप्रकाश मोड',
  
    no_active_alerts: 'तुमच्या क्षेत्रात कोणतीही सक्रिय सूचना नाही.',
    alert_severity: 'तीव्रता:',
    profile_edit: 'संपादित करा',
    profile_save: 'जतन करा',
    profile_name: 'नाव',
    profile_location: 'ठिकाण (उदा. वर्सोवा)',
    guest_fisher: 'अतिथी मच्छीमार / ऑफलाइन मोड',
    location_not_set: 'ठिकाण निश्चित केलेले नाही',
    no_phone: 'फोन नंबर जोडलेला नाही',
    vessel_emergency: 'जहाज आणि आणीबाणी',
    vessel_name: 'जहाजाचे नाव:',
    vessel_na: 'लागू नाही',
    registration_id: 'नोंदणी आयडी:',
    emergency_contact: 'आणीबाणी:',
    comma_separated: 'स्वल्पविरामाने वेगळे केलेले',
    none_set: 'काहीही सेट केलेले नाही',
    settings: 'सेटिंग्ज',
    active_language: 'सक्रिय भाषा:',
    sign_out: 'साइन आउट करा',
    sign_out_confirm: 'तुम्हाला खात्री आहे की तुम्हाला ओर्कामधून लॉग आउट करायचे आहे?',
    wet_hand_desc: 'टॅप लक्ष्य मोठे करते आणि उच्च-कॉन्ट्रास्ट लागू करते',
    enabled_64dp: 'सक्षम (64dp)',
    disabled_48dp: 'अक्षम (प्रमाणित 48dp)',
  },
  hi: {
    knots: 'नॉट',
    meters: 'मीटर',
    mps: 'मी/से',
    high_tide: 'उच्च ज्वार',
    nw: 'उत्तर-पश्चिम',
    high_probability_pfz: 'उच्च संभाव्यता मत्स्य पालन क्षेत्र',
    pfz_type: 'संभावित मत्स्य पालन क्षेत्र',
    cyclone_warning: 'चक्रवात चेतावनी',
    hazard: 'खतरा',
    coast_guard_station: 'तटरक्षक स्टेशन',
    rescue_type: 'बचाव',
    safe_navigation_route: 'सुरक्षित नेविगेशन मार्ग',
    route_type: 'मार्ग',
    imbl_buffer: 'अंतर्राष्ट्रीय समुद्री सीमा रेखा बफर',
    boundary_warning: 'सीमा चेतावनी',
    approaching_imbl: 'अंतर्राष्ट्रीय जलक्षेत्र के करीब',
    computed_route: 'ऊंची लहरों से बचने वाला मार्ग',
    type_query: 'अपनी क्वेरी यहाँ टाइप करें...',
    stop: 'रुकें',
    mic: 'माइक',
    send: 'भेजें',
    current_sea_state: 'वर्तमान समुद्र की स्थिति',
    wind_speed: 'हवा की गति:',
    wind_dir: 'हवा की दिशा:',
    wave_length: 'लहर की लंबाई:',
    wave_speed: 'लहर की गति:',
    temperature: 'तापमान:',
    tide: 'ज्वार:',
    pfz: 'संभावित मत्स्य पालन क्षेत्र',
    alerts: 'चेतावनी',
    imbl: 'अंतर्राष्ट्रीय समुद्री सीमा रेखा',
    rescue: 'बचाव',
    safe_route: 'सुरक्षित मार्ग',
    zone_details: 'क्षेत्र विवरण',
    confidence: 'आत्मविश्वास:',
    severity: 'गंभीरता:',
    contact: 'संपर्क:',
    close: 'बंद करें',
    permission_denied: 'अनुमति अस्वीकार कर दी गई',
    mic_access_required: 'वॉइस AI का उपयोग करने के लिए माइक्रोफ़ोन एक्सेस आवश्यक है।',
    ai_error_fallback: 'AI सेवा से कनेक्ट करने में विफल। ऑफ़लाइन कैश पर वापस जा रहा है...',
    app_title: 'ओर्का',
    nav_home: 'होम',
    nav_map: 'मानचित्र',
    nav_ai: 'ओर्का एआई',
    nav_alerts: 'चेतावनी',
    nav_profile: 'प्रोफ़ाइल',
    risk_low: 'कम जोखिम',
    risk_moderate: 'मध्यम जोखिम',
    risk_high: 'उच्च जोखिम',
    ask_orca: 'ओर्का से पूछें',
    emergency_sos: 'आपातकालीन (SOS)',
    ocean_conditions: 'समुद्र की स्थिति',
    fishing_intelligence: 'मत्स्य पालन बुद्धिमत्ता',
    cached_banner: 'कैश किया गया डेटा — पुराना डेटा',
    offline_mode: 'ऑफ़लाइन मोड',
    confirm: 'पुष्टि करें',
    cancel: 'रद्द करें',
    retry: 'पुनः प्रयास करें',
    wet_hand_mode: 'वेट-हैंड और धूप मोड',
  
    no_active_alerts: 'आपके क्षेत्र में कोई सक्रिय अलर्ट नहीं है।',
    alert_severity: 'गंभीरता:',
    profile_edit: 'संपादित करें',
    profile_save: 'सहेजें',
    profile_name: 'नाम',
    profile_location: 'स्थान (उदा. वर्सोवा)',
    guest_fisher: 'अतिथि मछुआरा / ऑफ़लाइन मोड',
    location_not_set: 'स्थान निर्धारित नहीं है',
    no_phone: 'कोई फोन नंबर लिंक नहीं है',
    vessel_emergency: 'पोत और आपातकाल',
    vessel_name: 'पोत का नाम:',
    vessel_na: 'लागू नहीं',
    registration_id: 'पंजीकरण आईडी:',
    emergency_contact: 'आपातकाल:',
    comma_separated: 'अल्पविराम से अलग',
    none_set: 'कोई सेट नहीं',
    settings: 'सेटिंग्स',
    active_language: 'सक्रिय भाषा:',
    sign_out: 'साइन आउट करें',
    sign_out_confirm: 'क्या आप वाकई ORCA से लॉग आउट करना चाहते हैं?',
    wet_hand_desc: 'टैप लक्ष्य को बड़ा करता है और उच्च-विपरीत लागू करता है',
    enabled_64dp: 'सक्षम (64dp)',
    disabled_48dp: 'अक्षम (मानक 48dp)',
  },
  en: {
    knots: 'knots',
    meters: 'meters',
    mps: 'm/s',
    high_tide: 'High Tide',
    nw: 'NW',
    high_probability_pfz: 'High Probability Potential Fishing Zone',
    pfz_type: 'Potential Fishing Zone',
    cyclone_warning: 'Cyclone Warning',
    hazard: 'hazard',
    coast_guard_station: 'Coast Guard Station',
    rescue_type: 'rescue',
    safe_navigation_route: 'Safe Navigation Route',
    route_type: 'route',
    imbl_buffer: 'International Maritime Boundary Line Buffer',
    boundary_warning: 'Boundary Warning',
    approaching_imbl: 'Approaching International Waters',
    computed_route: 'Computed route avoiding high wave crests',
    type_query: 'Type your query here...',
    stop: 'Stop',
    mic: 'Mic',
    send: 'Send',
    current_sea_state: 'Current Sea State',
    wind_speed: 'Wind Speed:',
    wind_dir: 'Wind Dir:',
    wave_length: 'Wave Length:',
    wave_speed: 'Wave Speed:',
    temperature: 'Temperature:',
    tide: 'Tide:',
    pfz: 'Potential Fishing Zone',
    alerts: 'Alerts',
    imbl: 'International Maritime Boundary Line',
    rescue: 'Rescue',
    safe_route: 'Safe Route',
    zone_details: 'Zone Details',
    confidence: 'Confidence:',
    severity: 'Severity:',
    contact: 'Contact:',
    close: 'CLOSE',
    permission_denied: 'Permission Denied',
    mic_access_required: 'Microphone access is required to use Voice AI.',
    ai_error_fallback: 'Failed to connect to AI Service. Falling back to offline cache...',
    app_title: 'ORCA',
    nav_home: 'Home',
    nav_map: 'Map',
    nav_ai: 'Ask ORCA',
    nav_alerts: 'Alerts',
    nav_profile: 'Profile',
    risk_low: 'LOW RISK',
    risk_moderate: 'MODERATE RISK',
    risk_high: 'HIGH RISK',
    ask_orca: 'Ask ORCA',
    emergency_sos: 'EMERGENCY (SOS)',
    ocean_conditions: 'Ocean Conditions',
    fishing_intelligence: 'Fishing Intelligence',
    cached_banner: 'Cached Data — Stale',
    offline_mode: 'Offline Mode',
    confirm: 'Confirm',
    cancel: 'Cancel',
    retry: 'Retry',
    wet_hand_mode: 'Wet-Hand & Glare Mode',
  
    no_active_alerts: 'No active alerts in your area.',
    alert_severity: 'Severity:',
    profile_edit: 'Edit',
    profile_save: 'Save',
    profile_name: 'Name',
    profile_location: 'Location (e.g. Versova)',
    guest_fisher: 'Guest Fisher / Offline Demo Mode',
    location_not_set: 'Location not set',
    no_phone: 'No phone number linked',
    vessel_emergency: 'Vessel & Emergency',
    vessel_name: 'Vessel Name:',
    vessel_na: 'N/A',
    registration_id: 'Registration ID:',
    emergency_contact: 'Emergency:',
    comma_separated: 'Comma separated',
    none_set: 'None set',
    settings: 'Settings',
    active_language: 'Active Language:',
    sign_out: 'Sign Out',
    sign_out_confirm: 'Are you sure you want to log out of ORCA?',
    wet_hand_desc: 'Enlarges tap targets and forces high-contrast',
    enabled_64dp: 'Enabled (64dp Target Active)',
    disabled_48dp: 'Disabled (Standard 48dp)',
  },
  gu: {
    type_query: 'તમારો પ્રશ્ન અહીં ટાઇપ કરો...',
    stop: 'થોભો',
    mic: 'માઇક',
    send: 'મોકલો',
    current_sea_state: 'વર્તમાન સમુદ્ર સ્થિતિ',
    wind_speed: 'પવનની ગતિ:',
    wind_dir: 'પવનની દિશા:',
    wave_length: 'મોજાની લંબાઈ:',
    wave_speed: 'મોજાની ગતિ:',
    temperature: 'તાપમાન:',
    tide: 'ભરતી:',
    pfz: 'સંભવિત માછીમારી ક્ષેત્ર',
    alerts: 'ચેતવણીઓ',
    imbl: 'આંતરરાષ્ટ્રીય દરિયાઈ સીમા રેખા',
    rescue: 'બચાવ',
    safe_route: 'સુરક્ષિત માર્ગ',
    zone_details: 'ક્ષેત્ર વિગતો',
    confidence: 'વિશ્વાસ:',
    severity: 'ગંભીરતા:',
    contact: 'સંપર્ક:',
    close: 'બંધ કરો',
    permission_denied: 'પરવાનગી નામંજૂર',
    mic_access_required: 'વૉઇસ AI નો ઉપયોગ કરવા માટે માઇક્રોફોનની ઍક્સેસ જરૂરી છે.',
    ai_error_fallback: 'AI સેવા સાથે કનેક્ટ કરવામાં નિષ્ફળ. ઑફલાઇન કૅશે પર પાછા જઈ રહ્યાં છીએ...',
    app_title: 'ઓર્કા',
    nav_home: 'હોમ',
    nav_map: 'નકશો',
    nav_ai: 'ઓર્કા AI',
    nav_alerts: 'ચેતવણીઓ',
    nav_profile: 'પ્રોફાઇલ',
    risk_low: 'ઓછું જોખમ',
    risk_moderate: 'મધ્યમ જોખમ',
    risk_high: 'વધુ જોખમ',
    ask_orca: 'ઓર્કાને પૂછો',
    emergency_sos: 'કટોકટી (SOS)',
    ocean_conditions: 'દરિયાઈ પરિસ્થિતિ',
    fishing_intelligence: 'માછીમારી માહિતી',
    cached_banner: 'કેશ્ડ ડેટા',
    offline_mode: 'ઑફલાઇન મોડ',
    confirm: 'ખાતરી કરો',
    cancel: 'રદ કરો',
    retry: 'ફરી પ્રયાસ કરો',
    wet_hand_mode: 'વેટ-હેન્ડ મોડ',
  
    no_active_alerts: 'તમારા વિસ્તારમાં કોઈ સક્રિય ચેતવણીઓ નથી.',
    alert_severity: 'ગંભીરતા:',
    profile_edit: 'સંપાદિત કરો',
    profile_save: 'સાચવો',
    profile_name: 'નામ',
    profile_location: 'સ્થાન (દા.ત. વર્સોવા)',
    guest_fisher: 'અતિથિ માછીમાર / ઑફલાઇન મોડ',
    location_not_set: 'સ્થાન સેટ કરેલ નથી',
    no_phone: 'કોઈ ફોન નંબર લિંક કરેલ નથી',
    vessel_emergency: 'જહાજ અને કટોકટી',
    vessel_name: 'જહાજનું નામ:',
    vessel_na: 'લાગુ નથી',
    registration_id: 'નોંધણી ID:',
    emergency_contact: 'કટોકટી:',
    comma_separated: 'અલ્પવિરામથી અલગ પડેલ',
    none_set: 'કોઈ સેટ નથી',
    settings: 'સેટિંગ્સ',
    active_language: 'સક્રિય ભાષા:',
    sign_out: 'સાઇન આઉટ કરો',
    sign_out_confirm: 'શું તમે ખરેખર ORCA માંથી લૉગ આઉટ કરવા માંગો છો?',
    wet_hand_desc: 'ટૅપ લક્ષ્યોને મોટા કરે છે અને ઉચ્ચ-કોન્ટ્રાસ્ટ લાગુ કરે છે',
    enabled_64dp: 'સક્ષમ (64dp)',
    disabled_48dp: 'અક્ષમ (પ્રમાણભૂત 48dp)',
  },
  ta: {
    type_query: 'உங்கள் கேள்வியை இங்கே தட்டச்சு செய்க...',
    stop: 'நிறுத்து',
    mic: 'மைக்',
    send: 'அனுப்பு',
    current_sea_state: 'தற்போதைய கடல் நிலை',
    wind_speed: 'காற்றின் வேகம்:',
    wind_dir: 'காற்றின் திசை:',
    wave_length: 'அலை நீளம்:',
    wave_speed: 'அலை வேகம்:',
    temperature: 'வெப்பநிலை:',
    tide: 'அலை:',
    pfz: 'சாத்தியமான மீன்பிடி மண்டலம்',
    alerts: 'எச்சரிக்கைகள்',
    imbl: 'சர்வதேச கடல் எல்லைக் கோடு',
    rescue: 'மீட்பு',
    safe_route: 'பாதுகாப்பான பாதை',
    zone_details: 'மண்டல விவரங்கள்',
    confidence: 'நம்பிக்கை:',
    severity: 'தீவிரம்:',
    contact: 'தொடர்பு:',
    close: 'மூடு',
    permission_denied: 'அனுமதி மறுக்கப்பட்டது',
    mic_access_required: 'குரல் AI ஐப் பயன்படுத்த மைக்ரோஃபோன் அணுகல் தேவை.',
    ai_error_fallback: 'AI சேவையுடன் இணைக்க முடியவில்லை. ஆஃப்லைன் தற்காலிக சேமிப்பிற்குத் திரும்புகிறது...',
    app_title: 'ஆர்கா',
    nav_home: 'முகப்பு',
    nav_map: 'வரைபடம்',
    nav_ai: 'ஆர்கா AI',
    nav_alerts: 'எச்சரிக்கைகள்',
    nav_profile: 'சுயவிவரம்',
    risk_low: 'குறைந்த ஆபத்து',
    risk_moderate: 'மிதமான ஆபத்து',
    risk_high: 'அதிக ஆபத்து',
    ask_orca: 'ஆர்காவிடம் கேளுங்கள்',
    emergency_sos: 'அவசர நிலை (SOS)',
    ocean_conditions: 'கடல் நிலைமை',
    fishing_intelligence: 'மீன்பிடி தகவல்கள்',
    cached_banner: 'தற்காலிக சேமிப்புத் தரவு',
    offline_mode: 'ஆஃப்லைன் பயன்முறை',
    confirm: 'உறுதி செய்',
    cancel: 'ரத்து செய்',
    retry: 'மீண்டும் முயற்சி செய்',
    wet_hand_mode: 'ஈரமான கை பயன்முறை',
  
    no_active_alerts: 'உங்கள் பகுதியில் எந்த செயலில் உள்ள எச்சரிக்கைகளும் இல்லை.',
    alert_severity: 'தீவிரம்:',
    profile_edit: 'திருத்து',
    profile_save: 'சேமி',
    profile_name: 'பெயர்',
    profile_location: 'இடம் (எ.கா. வெர்சோவா)',
    guest_fisher: 'விருந்தினர் மீனவர் / ஆஃப்லைன் பயன்முறை',
    location_not_set: 'இடம் அமைக்கப்படவில்லை',
    no_phone: 'தொலைபேசி எண் இணைக்கப்படவில்லை',
    vessel_emergency: 'கப்பல் & அவசரநிலை',
    vessel_name: 'கப்பலின் பெயர்:',
    vessel_na: 'பொருந்தாது',
    registration_id: 'பதிவு ஐடி:',
    emergency_contact: 'அவசரநிலை:',
    comma_separated: 'கமா மூலம் பிரிக்கப்பட்டுள்ளது',
    none_set: 'எதுவும் அமைக்கப்படவில்லை',
    settings: 'அமைப்புகள்',
    active_language: 'செயலில் உள்ள மொழி:',
    sign_out: 'வெளியேறு',
    sign_out_confirm: 'நீங்கள் ORCA இலிருந்து வெளியேற விரும்புகிறீர்களா?',
    wet_hand_desc: 'தட்டும் இலக்குகளை பெரிதாக்குகிறது மற்றும் அதிக கான்ட்ராஸ்ட்டை கட்டாயப்படுத்துகிறது',
    enabled_64dp: 'இயக்கப்பட்டது (64dp)',
    disabled_48dp: 'முடக்கப்பட்டது (நிலையான 48dp)',
  },

  bn: {
    type_query: 'আপনার প্রশ্ন এখানে লিখুন...',
    stop: 'থামুন',
    mic: 'মাইক',
    send: 'পাঠান',
    current_sea_state: 'বর্তমান সমুদ্রের অবস্থা',
    wind_speed: 'বাতাসের গতি:',
    wind_dir: 'বাতাসের দিক:',
    wave_length: 'ঢেউয়ের দৈর্ঘ্য:',
    wave_speed: 'ঢেউয়ের গতি:',
    temperature: 'তাপমাত্রা:',
    tide: 'জোয়ার:',
    pfz: 'সম্ভাব্য মাছ ধরার অঞ্চল',
    alerts: 'সতর্কতা',
    imbl: 'আন্তর্জাতিক সামুদ্রিক সীমানা রেখা',
    rescue: 'উদ্ধার',
    safe_route: 'নিরাপদ পথ',
    zone_details: 'অঞ্চলের বিবরণ',
    confidence: 'আত্মবিশ্বাস:',
    severity: 'তীব্রতা:',
    contact: 'যোগাযোগ:',
    close: 'বন্ধ করুন',
    permission_denied: 'অনুমতি অস্বীকার করা হয়েছে',
    mic_access_required: 'ভয়েস এআই ব্যবহার করতে মাইক্রোফোন অ্যাক্সেস প্রয়োজন।',
    ai_error_fallback: 'এআই পরিষেবার সাথে সংযোগ করতে ব্যর্থ। অফলাইন ক্যাশে ফিরে যাচ্ছে...',
    app_title: 'অরকা',
    nav_home: 'হোম',
    nav_map: 'মানচিত্র',
    nav_ai: 'অরকা এআই',
    nav_alerts: 'সতর্কতা',
    nav_profile: 'প্রোফাইল',
    risk_low: 'কম ঝুঁকি',
    risk_moderate: 'মাঝারি ঝুঁকি',
    risk_high: 'উচ্চ ঝুঁকি',
    ask_orca: 'অরকাকে জিজ্ঞাসা করুন',
    emergency_sos: 'জরুরী অবস্থা (SOS)',
    ocean_conditions: 'সমুদ্রের অবস্থা',
    fishing_intelligence: 'ফিশিং ইন্টেলিজেন্স',
    cached_banner: 'ক্যাশে করা ডেটা — পুরনো',
    offline_mode: 'অফলাইন মোড',
    confirm: 'নিশ্চিত করুন',
    cancel: 'বাতিল করুন',
    retry: 'পুনরায় চেষ্টা করুন',
    wet_hand_mode: 'ওয়েট-হ্যান্ড মোড',
    knots: 'নটস',
    meters: 'মিটার',
    mps: 'মি/সে',
    high_tide: 'উচ্চ জোয়ার',
    nw: 'উত্তর-পশ্চিম',
    high_probability_pfz: 'উচ্চ সম্ভাব্য মাছ ধরার অঞ্চল',
    pfz_type: 'সম্ভাব্য মাছ ধরার অঞ্চল',
    cyclone_warning: 'ঘূর্ণিঝড় সতর্কতা',
    hazard: 'বিপদ',
    coast_guard_station: 'কোস্ট গার্ড স্টেশন',
    rescue_type: 'উদ্ধার',
    safe_navigation_route: 'নিরাপদ নেভিগেশন পথ',
    route_type: 'পথ',
    imbl_buffer: 'আন্তর্জাতিক সামুদ্রিক সীমানা রেখা বাফার',
    boundary_warning: 'সীমানা সতর্কতা',
    approaching_imbl: 'আন্তর্জাতিক জলসীমার দিকে এগোচ্ছে',
    computed_route: 'উঁচু ঢেউ এড়ানোর পথ',
  
    no_active_alerts: 'আপনার এলাকায় কোনো সক্রিয় সতর্কতা নেই।',
    alert_severity: 'তীব্রতা:',
    profile_edit: 'সম্পাদনা করুন',
    profile_save: 'সংরক্ষণ করুন',
    profile_name: 'নাম',
    profile_location: 'অবস্থান (যেমন ভার্সোভা)',
    guest_fisher: 'অতিথি জেলে / অফলাইন মোড',
    location_not_set: 'অবস্থান সেট করা হয়নি',
    no_phone: 'কোনো ফোন নম্বর লিঙ্ক করা নেই',
    vessel_emergency: 'জাহাজ এবং জরুরি অবস্থা',
    vessel_name: 'জাহাজের নাম:',
    vessel_na: 'প্রযোজ্য নয়',
    registration_id: 'নিবন্ধন আইডি:',
    emergency_contact: 'জরুরি অবস্থা:',
    comma_separated: 'কমা দিয়ে আলাদা করা',
    none_set: 'কিছুই সেট করা হয়নি',
    settings: 'সেটিংস',
    active_language: 'সক্রিয় ভাষা:',
    sign_out: 'সাইন আউট করুন',
    sign_out_confirm: 'আপনি কি সত্যিই ORCA থেকে লগ আউট করতে চান?',
    wet_hand_desc: 'ট্যাপ লক্ষ্যগুলি বড় করে এবং উচ্চ-কন্ট্রাস্ট জোরদার করে',
    enabled_64dp: 'সক্ষম (64dp)',
    disabled_48dp: 'অক্ষম (স্ট্যান্ডার্ড 48dp)',
  },
  or: {
    type_query: 'ଆପଣଙ୍କ ପ୍ରଶ୍ନ ଏଠାରେ ଲେଖନ୍ତୁ...',
    stop: 'ବନ୍ଦ କରନ୍ତୁ',
    mic: 'ମାଇକ୍',
    send: 'ପଠାନ୍ତୁ',
    current_sea_state: 'ବର୍ତ୍ତମାନ ସମୁଦ୍ର ସ୍ଥିତି',
    wind_speed: 'ପବନର ଗତି:',
    wind_dir: 'ପବନର ଦିଗ:',
    wave_length: 'ଲହରୀ ଲମ୍ବ:',
    wave_speed: 'ଲହରୀ ଗତି:',
    temperature: 'ତାପମାତ୍ରା:',
    tide: 'ଜୁଆର:',
    pfz: 'ସମ୍ଭାବ୍ୟ ମାଛ ଧରା ଅଞ୍ଚଳ',
    alerts: 'ସତର୍କ ସୂଚନା',
    imbl: 'ଆନ୍ତର୍ଜାତୀୟ ସମୁଦ୍ର ସୀମା ରେଖା',
    rescue: 'ଉଦ୍ଧାର',
    safe_route: 'ସୁରକ୍ଷିତ ମାର୍ଗ',
    zone_details: 'ଅଞ୍ଚଳ ବିବରଣୀ',
    confidence: 'ବିଶ୍ୱାସ:',
    severity: 'ଗମ୍ଭୀରତା:',
    contact: 'ଯୋଗାଯୋଗ:',
    close: 'ବନ୍ଦ କରନ୍ତୁ',
    permission_denied: 'ଅନୁମତି ଅସ୍ୱୀକାର କରାଯାଇଛି',
    mic_access_required: 'ଭଏସ୍ AI ବ୍ୟବହାର କରିବାକୁ ମାଇକ୍ରୋଫୋନ୍ ଆକ୍ସେସ୍ ଆବଶ୍ୟକ।',
    ai_error_fallback: 'AI ସେବା ସହିତ ସଂଯୋଗ କରିବାରେ ବିଫଳ। ଅଫଲାଇନ୍ କ୍ୟାସେକୁ ଫେରୁଛି...',
    app_title: 'ଓର୍କା',
    nav_home: 'ହୋମ୍',
    nav_map: 'ମ୍ୟାପ୍',
    nav_ai: 'ଓର୍କା AI',
    nav_alerts: 'ସତର୍କ ସୂଚନା',
    nav_profile: 'ପ୍ରୋଫାଇଲ୍',
    risk_low: 'କମ୍ ବିପଦ',
    risk_moderate: 'ମଧ୍ୟମ ବିପଦ',
    risk_high: 'ଉଚ୍ଚ ବିପଦ',
    ask_orca: 'ଓର୍କାକୁ ପଚାରନ୍ତୁ',
    emergency_sos: 'ଜରୁରୀକାଳୀନ (SOS)',
    ocean_conditions: 'ସମୁଦ୍ର ସ୍ଥିତି',
    fishing_intelligence: 'ଫିଶିଂ ଇଣ୍ଟେଲିଜେନ୍ସ',
    cached_banner: 'କ୍ୟାସ୍ କରାଯାଇଥିବା ଡାଟା',
    offline_mode: 'ଅଫଲାଇନ୍ ମୋଡ୍',
    confirm: 'ନିଶ୍ଚିତ କରନ୍ତୁ',
    cancel: 'ବାତିଲ କରନ୍ତୁ',
    retry: 'ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ',
    wet_hand_mode: 'ୱେଟ୍-ହ୍ୟାଣ୍ଡ ମୋଡ୍',
    knots: 'ନଟ୍',
    meters: 'ମିଟର',
    mps: 'ମି/ସେ',
    high_tide: 'ଉଚ୍ଚ ଜୁଆର',
    nw: 'ଉତ୍ତର-ପଶ୍ଚିମ',
    high_probability_pfz: 'ଉଚ୍ଚ ସମ୍ଭାବ୍ୟ ମାଛ ଧରା ଅଞ୍ଚଳ',
    pfz_type: 'ସମ୍ଭାବ୍ୟ ମାଛ ଧରା ଅଞ୍ଚଳ',
    cyclone_warning: 'ବାତ୍ୟା ସତର୍କ ସୂଚନା',
    hazard: 'ବିପଦ',
    coast_guard_station: 'କୋଷ୍ଟ ଗାର୍ଡ ଷ୍ଟେସନ୍',
    rescue_type: 'ଉଦ୍ଧାର',
    safe_navigation_route: 'ସୁରକ୍ଷିତ ନେଭିଗେସନ୍ ମାର୍ଗ',
    route_type: 'ମାର୍ଗ',
    imbl_buffer: 'ଆନ୍ତର୍ଜାତୀୟ ସମୁଦ୍ର ସୀମା ରେଖା ବଫର୍',
    boundary_warning: 'ସୀମା ସତର୍କ ସୂଚନା',
    approaching_imbl: 'ଆନ୍ତର୍ଜାତୀୟ ଜଳସୀମା ଆଡକୁ ଯାଉଛି',
    computed_route: 'ଉଚ୍ଚ ଲହରୀ ଏଡାଇବା ମାର୍ଗ',
  
    no_active_alerts: 'ଆପଣଙ୍କ ଅଞ୍ଚଳରେ କୌଣସି ସକ୍ରିୟ ସତର୍କ ସୂଚନା ନାହିଁ।',
    alert_severity: 'ଗମ୍ଭୀରତା:',
    profile_edit: 'ସମ୍ପାଦନା କରନ୍ତୁ',
    profile_save: 'ସେଭ୍ କରନ୍ତୁ',
    profile_name: 'ନାମ',
    profile_location: 'ସ୍ଥାନ (ଯେପରିକି ଭର୍ସୋଭା)',
    guest_fisher: 'ଅତିଥି ମତ୍ସ୍ୟଜୀବୀ / ଅଫଲାଇନ୍ ମୋଡ୍',
    location_not_set: 'ସ୍ଥାନ ସେଟ୍ କରାଯାଇ ନାହିଁ',
    no_phone: 'କୌଣସି ଫୋନ୍ ନମ୍ବର ଲିଙ୍କ୍ ହୋଇନାହିଁ',
    vessel_emergency: 'ଜାହାଜ ଏବଂ ଜରୁରୀକାଳୀନ',
    vessel_name: 'ଜାହାଜର ନାମ:',
    vessel_na: 'ପ୍ରଯୁଜ୍ୟ ନୁହେଁ',
    registration_id: 'ପଞ୍ଜୀକରଣ ID:',
    emergency_contact: 'ଜରୁରୀକାଳୀନ:',
    comma_separated: 'କମା ଦ୍ୱାରା ପୃଥକ',
    none_set: 'କିଛି ସେଟ୍ ହୋଇନାହିଁ',
    settings: 'ସେଟିଂସମୂହ',
    active_language: 'ସକ୍ରିୟ ଭାଷା:',
    sign_out: 'ସାଇନ୍ ଆଉଟ୍ କରନ୍ତୁ',
    sign_out_confirm: 'ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ ORCA ରୁ ଲଗ୍ ଆଉଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି?',
    wet_hand_desc: 'ଟ୍ୟାପ୍ ଲକ୍ଷ୍ୟଗୁଡ଼ିକୁ ବଡ଼ କରେ ଏବଂ ଉଚ୍ଚ-କଣ୍ଟ୍ରାଷ୍ଟ ଲାଗୁ କରେ',
    enabled_64dp: 'ସକ୍ଷମ (64dp)',
    disabled_48dp: 'ଅକ୍ଷମ (ଷ୍ଟାଣ୍ଡାର୍ଡ 48dp)',
  },
  ml: {
    type_query: 'നിങ്ങളുടെ ചോദ്യം ഇവിടെ നൽകുക...',
    stop: 'നിർത്തുക',
    mic: 'മൈക്ക്',
    send: 'അയക്കുക',
    current_sea_state: 'നിലവിലെ കടൽ അവസ്ഥ',
    wind_speed: 'കാറ്റിന്റെ വേഗത:',
    wind_dir: 'കാറ്റിന്റെ ദിശ:',
    wave_length: 'തിരമാലയുടെ നീളം:',
    wave_speed: 'തിരമാലയുടെ വേഗത:',
    temperature: 'താപനില:',
    tide: 'വേലിയേറ്റം:',
    pfz: 'സാധ്യതാ മത്സ്യബന്ധന മേഖല',
    alerts: 'മുന്നറിയിപ്പുകൾ',
    imbl: 'അന്താരാഷ്ട്ര സമുദ്ര അതിർത്തി രേഖ',
    rescue: 'രക്ഷപ്പെടുത്തൽ',
    safe_route: 'സുരക്ഷിതമായ പാത',
    zone_details: 'മേഖലാ വിവരങ്ങൾ',
    confidence: 'വിശ്വാസം:',
    severity: 'തീവ്രത:',
    contact: 'ബന്ധപ്പെടുക:',
    close: 'അടയ്ക്കുക',
    permission_denied: 'അനുമതി നിഷേധിച്ചു',
    mic_access_required: 'വോയ്‌സ് AI ഉപയോഗിക്കാൻ മൈക്രോഫോൺ ആക്‌സസ് ആവശ്യമാണ്.',
    ai_error_fallback: 'AI സേവനവുമായി ബന്ധിപ്പിക്കുന്നതിൽ പരാജയപ്പെട്ടു. ഓഫ്‌ലൈൻ കാഷെയിലേക്ക് മടങ്ങുന്നു...',
    app_title: 'ഓർക്ക',
    nav_home: 'ഹോം',
    nav_map: 'മാപ്പ്',
    nav_ai: 'ഓർക്ക AI',
    nav_alerts: 'മുന്നറിയിപ്പുകൾ',
    nav_profile: 'പ്രൊഫൈൽ',
    risk_low: 'കുറഞ്ഞ അപകടസാധ്യത',
    risk_moderate: 'മിതമായ അപകടസാധ്യത',
    risk_high: 'ഉയർന്ന അപകടസാധ്യത',
    ask_orca: 'ഓർക്കയോട് ചോദിക്കുക',
    emergency_sos: 'അടിയന്തരാവസ്ഥ (SOS)',
    ocean_conditions: 'കടൽ അവസ്ഥ',
    fishing_intelligence: 'ഫിഷിംഗ് ഇന്റലിജൻസ്',
    cached_banner: 'കാഷെ ചെയ്ത ഡാറ്റ',
    offline_mode: 'ഓഫ്‌ലൈൻ മോഡ്',
    confirm: 'ഉറപ്പാക്കുക',
    cancel: 'റദ്ദാക്കുക',
    retry: 'വീണ്ടും ശ്രമിക്കുക',
    wet_hand_mode: 'വെറ്റ്-ഹാൻഡ് മോഡ്',
    knots: 'നോട്ട്സ്',
    meters: 'മീറ്റർ',
    mps: 'മീ/സെ',
    high_tide: 'ഉയർന്ന വേലിയേറ്റം',
    nw: 'വടക്ക്-പടിഞ്ഞാറ്',
    high_probability_pfz: 'ഉയർന്ന സാധ്യതാ മത്സ്യബന്ധന മേഖല',
    pfz_type: 'സാധ്യതാ മത്സ്യബന്ധന മേഖല',
    cyclone_warning: 'ചുഴലിക്കാറ്റ് മുന്നറിയിപ്പ്',
    hazard: 'അപകടം',
    coast_guard_station: 'കോസ്റ്റ് ഗാർഡ് സ്റ്റേഷൻ',
    rescue_type: 'രക്ഷപ്പെടുത്തൽ',
    safe_navigation_route: 'സുരക്ഷിതമായ നാവിഗേഷൻ പാത',
    route_type: 'പാത',
    imbl_buffer: 'അന്താരാഷ്ട്ര സമുദ്ര അതിർത്തി രേഖാ ബഫർ',
    boundary_warning: 'അതിർത്തി മുന്നറിയിപ്പ്',
    approaching_imbl: 'അന്താരാഷ്ട്ര ജലാശയത്തിലേക്ക് പ്രവേശിക്കുന്നു',
    computed_route: 'ഉയർന്ന തിരമാലകൾ ഒഴിവാക്കുന്ന പാത',
  
    no_active_alerts: 'നിങ്ങളുടെ പ്രദേശത്ത് സജീവമായ മുന്നറിയിപ്പുകളൊന്നുമില്ല.',
    alert_severity: 'തീവ്രത:',
    profile_edit: 'എഡിറ്റ് ചെയ്യുക',
    profile_save: 'സേവ് ചെയ്യുക',
    profile_name: 'പേര്',
    profile_location: 'സ്ഥലം (ഉദാ: വെർസോവ)',
    guest_fisher: 'അതിഥി മത്സ്യത്തൊഴിലാളി / ഓഫ്‌ലൈൻ മോഡ്',
    location_not_set: 'സ്ഥലം നൽകിയിട്ടില്ല',
    no_phone: 'ഫോൺ നമ്പർ ലിങ്ക് ചെയ്തിട്ടില്ല',
    vessel_emergency: 'കപ്പലും അടിയന്തരാവസ്ഥയും',
    vessel_name: 'കപ്പലിന്റെ പേര്:',
    vessel_na: 'ബാധകമല്ല',
    registration_id: 'രജിസ്ട്രേഷൻ ഐഡി:',
    emergency_contact: 'അടിയന്തരാവസ്ഥ:',
    comma_separated: 'കോമ ഉപയോഗിച്ച് വേർതിരിച്ചത്',
    none_set: 'ഒന്നും നൽകിയിട്ടില്ല',
    settings: 'ക്രമീകരണങ്ങൾ',
    active_language: 'സജീവ ഭാഷ:',
    sign_out: 'സൈൻ ഔട്ട് ചെയ്യുക',
    sign_out_confirm: 'ORCA ൽ നിന്ന് ലോഗ് ഔട്ട് ചെയ്യണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?',
    wet_hand_desc: 'ടാപ്പ് ടാർഗെറ്റുകൾ വലുതാക്കുകയും ഉയർന്ന കോൺട്രാസ്റ്റ് പ്രയോഗിക്കുകയും ചെയ്യുന്നു',
    enabled_64dp: 'പ്രവർത്തനക്ഷമമാക്കി (64dp)',
    disabled_48dp: 'പ്രവർത്തനരഹിതമാക്കി (സ്റ്റാൻഡേർഡ് 48dp)',
  },
  te: {
    type_query: 'మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...',
    stop: 'ఆపండి',
    mic: 'మైక్',
    send: 'పంపండి',
    current_sea_state: 'ప్రస్తుత సముద్ర స్థితి',
    wind_speed: 'గాలి వేగం:',
    wind_dir: 'గాలి దిశ:',
    wave_length: 'అల పొడవు:',
    wave_speed: 'అల వేగం:',
    temperature: 'ఉష్ణోగ్రత:',
    tide: 'ఆటుపోట్లు:',
    pfz: 'సంభావ్య ఫిషింగ్ జోన్',
    alerts: 'హెచ్చరికలు',
    imbl: 'అంతర్జాతీయ సముద్ర సరిహద్దు రేఖ',
    rescue: 'రెస్క్యూ',
    safe_route: 'సురక్షిత మార్గం',
    zone_details: 'జోన్ వివరాలు',
    confidence: 'నమ్మకం:',
    severity: 'తీవ్రత:',
    contact: 'సంప్రదించండి:',
    close: 'మూసివేయండి',
    permission_denied: 'అనుమతి నిరాకరించబడింది',
    mic_access_required: 'వాయిస్ AIని ఉపయోగించడానికి మైక్రోఫోన్ యాక్సెస్ అవసరం.',
    ai_error_fallback: 'AI సేవకు కనెక్ట్ చేయడంలో విఫలమైంది. ఆఫ్‌లైన్ కాష్‌కు తిరిగి వెళుతోంది...',
    app_title: 'ఓర్కా',
    nav_home: 'హోమ్',
    nav_map: 'మ్యాప్',
    nav_ai: 'ఓర్కా AI',
    nav_alerts: 'హెచ్చరికలు',
    nav_profile: 'ప్రొఫైల్',
    risk_low: 'తక్కువ ప్రమాదం',
    risk_moderate: 'మితమైన ప్రమాదం',
    risk_high: 'అధిక ప్రమాదం',
    ask_orca: 'ఓర్కాను అడగండి',
    emergency_sos: 'అత్యవసర (SOS)',
    ocean_conditions: 'సముద్ర పరిస్థితులు',
    fishing_intelligence: 'ఫిషింగ్ ఇంటెలిజెన్స్',
    cached_banner: 'కాష్ చేయబడిన డేటా',
    offline_mode: 'ఆఫ్‌లైన్ మోడ్',
    confirm: 'నిర్ధారించండి',
    cancel: 'రద్దు చేయండి',
    retry: 'మళ్లీ ప్రయత్నించండి',
    wet_hand_mode: 'వెట్-హ్యాండ్ మోడ్',
    knots: 'నాట్స్',
    meters: 'మీటర్లు',
    mps: 'మీ/సె',
    high_tide: 'హై టైడ్',
    nw: 'వాయువ్యం',
    high_probability_pfz: 'అధిక సంభావ్య ఫిషింగ్ జోన్',
    pfz_type: 'సంభావ్య ఫిషింగ్ జోన్',
    cyclone_warning: 'తుఫాను హెచ్చరిక',
    hazard: 'ప్రమాదం',
    coast_guard_station: 'కోస్ట్ గార్డ్ స్టేషన్',
    rescue_type: 'రెస్క్యూ',
    safe_navigation_route: 'సురక్షిత నావిగేషన్ మార్గం',
    route_type: 'మార్గం',
    imbl_buffer: 'అంతర్జాతీయ సముద్ర సరిహద్దు రేఖ బఫర్',
    boundary_warning: 'సరిహద్దు హెచ్చరిక',
    approaching_imbl: 'అంతర్జాతీయ జలాలకు సమీపిస్తోంది',
    computed_route: 'అధిక అలలను నివారించే మార్గం',
  
    no_active_alerts: 'మీ ప్రాంతంలో చురుకైన హెచ్చరికలు లేవు.',
    alert_severity: 'తీవ్రత:',
    profile_edit: 'సవరించు',
    profile_save: 'సేవ్ చేయండి',
    profile_name: 'పేరు',
    profile_location: 'స్థానం (ఉదా. వెర్సోవా)',
    guest_fisher: 'అతిథి మత్స్యకారుడు / ఆఫ్‌లైన్ మోడ్',
    location_not_set: 'స్థానం సెట్ చేయబడలేదు',
    no_phone: 'ఫోన్ నంబర్ లింక్ చేయబడలేదు',
    vessel_emergency: 'నౌక & అత్యవసర',
    vessel_name: 'నౌక పేరు:',
    vessel_na: 'వర్తించదు',
    registration_id: 'రిజిస్ట్రేషన్ ID:',
    emergency_contact: 'అత్యవసర:',
    comma_separated: 'కామాలతో వేరు చేయబడింది',
    none_set: 'ఏదీ సెట్ చేయలేదు',
    settings: 'సెట్టింగ్‌లు',
    active_language: 'సక్రియ భాష:',
    sign_out: 'సైన్ అవుట్ చేయండి',
    sign_out_confirm: 'మీరు ఖచ్చితంగా ORCA నుండి లాగ్ అవుట్ చేయాలనుకుంటున్నారా?',
    wet_hand_desc: 'ట్యాప్ లక్ష్యాలను పెద్దవి చేస్తుంది మరియు అధిక-కాంట్రాస్ట్‌ను బలవంతం చేస్తుంది',
    enabled_64dp: 'ప్రారంభించబడింది (64dp)',
    disabled_48dp: 'నిలిపివేయబడింది (ప్రామాణిక 48dp)',
  },
  kn: {
    type_query: 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
    stop: 'ನಿಲ್ಲಿಸಿ',
    mic: 'ಮೈಕ್',
    send: 'ಕಳುಹಿಸಿ',
    current_sea_state: 'ಪ್ರಸ್ತುತ ಸಮುದ್ರ ಸ್ಥಿತಿ',
    wind_speed: 'ಗಾಳಿಯ ವೇಗ:',
    wind_dir: 'ಗಾಳಿಯ ದಿಕ್ಕು:',
    wave_length: 'ಅಲೆಯ ಉದ್ದ:',
    wave_speed: 'ಅಲೆಯ ವೇಗ:',
    temperature: 'ತಾಪಮಾನ:',
    tide: 'ಉಬ್ಬರವಿಳಿತ:',
    pfz: 'ಸಂಭಾವ್ಯ ಮೀನುಗಾರಿಕಾ ವಲಯ',
    alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    imbl: 'ಅಂತರರಾಷ್ಟ್ರೀಯ ಕಡಲ ಗಡಿ ರೇಖೆ',
    rescue: 'ರಕ್ಷಣಾ ಕಾರ್ಯಾಚರಣೆ',
    safe_route: 'ಸುರಕ್ಷಿತ ಮಾರ್ಗ',
    zone_details: 'ವಲಯದ ವಿವರಗಳು',
    confidence: 'ವಿಶ್ವಾಸ:',
    severity: 'ತೀವ್ರತೆ:',
    contact: 'ಸಂಪರ್ಕ:',
    close: 'ಮುಚ್ಚಿ',
    permission_denied: 'ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ',
    mic_access_required: 'ಧ್ವನಿ AI ಬಳಸಲು ಮೈಕ್ರೊಫೋನ್ ಪ್ರವೇಶದ ಅಗತ್ಯವಿದೆ.',
    ai_error_fallback: 'AI ಸೇವೆಗೆ ಸಂಪರ್ಕಿಸಲು ವಿಫಲವಾಗಿದೆ. ಆಫ್‌ಲೈನ್ ಸಂಗ್ರಹಕ್ಕೆ ಹಿಂತಿರುಗಲಾಗುತ್ತಿದೆ...',
    app_title: 'ಓರ್ಕಾ',
    nav_home: 'ಮುಖಪುಟ',
    nav_map: 'ನಕ್ಷೆ',
    nav_ai: 'ಓರ್ಕಾ AI',
    nav_alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    nav_profile: 'ಪ್ರೊಫೈಲ್',
    risk_low: 'ಕಡಿಮೆ ಅಪಾಯ',
    risk_moderate: 'ಮಧ್ಯಮ ಅಪಾಯ',
    risk_high: 'ಹೆಚ್ಚಿನ ಅಪಾಯ',
    ask_orca: 'ಓರ್ಕಾಗೆ ಕೇಳಿ',
    emergency_sos: 'ತುರ್ತು (SOS)',
    ocean_conditions: 'ಸಮುದ್ರ ಸ್ಥಿತಿ',
    fishing_intelligence: 'ಮೀನುಗಾರಿಕಾ ಬುದ್ಧಿವಂತಿಕೆ',
    cached_banner: 'ಸಂಗ್ರಹಿಸಲಾದ ಡೇಟಾ',
    offline_mode: 'ಆಫ್‌ಲೈನ್ ಮೋಡ್',
    confirm: 'ಖಚಿತಪಡಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    wet_hand_mode: 'ವೆಟ್-ಹ್ಯಾಂಡ್ ಮೋಡ್',
    knots: 'ನಾಟ್ಸ್',
    meters: 'ಮೀಟರ್',
    mps: 'ಮೀ/ಸೆ',
    high_tide: 'ಹೆಚ್ಚಿನ ಉಬ್ಬರವಿಳಿತ',
    nw: 'ವಾಯುವ್ಯ',
    high_probability_pfz: 'ಹೆಚ್ಚಿನ ಸಂಭಾವ್ಯ ಮೀನುಗಾರಿಕಾ ವಲಯ',
    pfz_type: 'ಸಂಭಾವ್ಯ ಮೀನುಗಾರಿಕಾ ವಲಯ',
    cyclone_warning: 'ಚಂಡಮಾರುತ ಎಚ್ಚರಿಕೆ',
    hazard: 'ಅಪಾಯ',
    coast_guard_station: 'ಕೋಸ್ಟ್ ಗಾರ್ಡ್ ಸ್ಟೇಷನ್',
    rescue_type: 'ರಕ್ಷಣೆ',
    safe_navigation_route: 'ಸುರಕ್ಷಿತ ಸಂಚರಣೆ ಮಾರ್ಗ',
    route_type: 'ಮಾರ್ಗ',
    imbl_buffer: 'ಅಂತರರಾಷ್ಟ್ರೀಯ ಕಡಲ ಗಡಿ ರೇಖೆಯ ಬಫರ್',
    boundary_warning: 'ಗಡಿ ಎಚ್ಚರಿಕೆ',
    approaching_imbl: 'ಅಂತರರಾಷ್ಟ್ರೀಯ ಜಲಪ್ರದೇಶವನ್ನು ಸಮೀಪಿಸುತ್ತಿದೆ',
    computed_route: 'ಎತ್ತರದ ಅಲೆಗಳನ್ನು ತಪ್ಪಿಸುವ ಮಾರ್ಗ',
  
    no_active_alerts: 'ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಯಾವುದೇ ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ.',
    alert_severity: 'ತೀವ್ರತೆ:',
    profile_edit: 'ತಿದ್ದುಪಡಿ',
    profile_save: 'ಉಳಿಸಿ',
    profile_name: 'ಹೆಸರು',
    profile_location: 'ಸ್ಥಳ (ಉದಾ. ವರ್ಸೋವಾ)',
    guest_fisher: 'ಅತಿಥಿ ಮೀನುಗಾರ / ಆಫ್‌ಲೈನ್ ಮೋಡ್',
    location_not_set: 'ಸ್ಥಳವನ್ನು ಹೊಂದಿಸಲಾಗಿಲ್ಲ',
    no_phone: 'ಫೋನ್ ಸಂಖ್ಯೆ ಲಿಂಕ್ ಆಗಿಲ್ಲ',
    vessel_emergency: 'ಹಡಗು ಮತ್ತು ತುರ್ತು',
    vessel_name: 'ಹಡಗಿನ ಹೆಸರು:',
    vessel_na: 'ಅನ್ವಯಿಸುವುದಿಲ್ಲ',
    registration_id: 'ನೋಂದಣಿ ಐಡಿ:',
    emergency_contact: 'ತುರ್ತು ಪರಿಸ್ಥಿತಿ:',
    comma_separated: 'ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರ್ಪಡಿಸಲಾಗಿದೆ',
    none_set: 'ಯಾವುದನ್ನೂ ಹೊಂದಿಸಿಲ್ಲ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    active_language: 'ಸಕ್ರಿಯ ಭಾಷೆ:',
    sign_out: 'ಸೈನ್ ಔಟ್ ಮಾಡಿ',
    sign_out_confirm: 'ನೀವು ORCA ನಿಂದ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಖಚಿತವಾಗಿದ್ದೀರಾ?',
    wet_hand_desc: 'ಟ್ಯಾಪ್ ಗುರಿಗಳನ್ನು ದೊಡ್ಡದಾಗಿಸುತ್ತದೆ ಮತ್ತು ಹೆಚ್ಚಿನ-ಕಾಂಟ್ರಾಸ್ಟ್ ಅನ್ನು ಒತ್ತಾಯಿಸುತ್ತದೆ',
    enabled_64dp: 'ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ (64dp)',
    disabled_48dp: 'ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ (ಪ್ರಮಾಣಿತ 48dp)',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => Promise<void>;
  t: (key: string) => string;
  supportedLanguages: LanguageOption[];
}

const STORAGE_KEY_LANGUAGE = '@orca_user_language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>('mr'); // Default to Marathi for artisanal persona

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY_LANGUAGE)
      .then((saved) => {
        if (saved && (saved in TRANSLATIONS)) {
          setLanguageState(saved as SupportedLanguage);
        }
      })
      .catch((err) => {
        console.warn('Failed to load user language:', err);
      });
  }, []);

  const setLanguage = async (newLang: SupportedLanguage) => {
    setLanguageState(newLang);
    try {
      await AsyncStorage.setItem(STORAGE_KEY_LANGUAGE, newLang);
    } catch (err) {
      console.warn('Failed to save user language:', err);
    }
  };

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        supportedLanguages: SUPPORTED_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
